apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "workload-identity-sa"
      containers:
        - name: mycontainer
          image: "<ACRNAME>.azurecr.io/todo:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: KeyVaultName
              value: "<KEYVAULTNAME>"
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secret-provider-name"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "<CLIENTID>"
  labels:
    azure.workload.identity/use: "true"
  name: "workload-identity-sa"
  namespace: "default"

---
kind: Service
apiVersion: v1
metadata:
  name: todo
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
